# Generated by Django 5.1.4 on 2026-04-17 12:42

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, help_text='Meta description for SEO')),
                ('keywords', models.CharField(blank=True, help_text='Comma-separated SEO keywords', max_length=500)),
                ('slug', models.SlugField(help_text='Unique URL path (auto-generated from title if left blank)', max_length=255, unique=True)),
                ('og_title', models.CharField(blank=True, help_text='Leave blank to use page title', max_length=255)),
                ('og_description', models.TextField(blank=True, help_text='Leave blank to use description')),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='uploads/og_images/')),
                ('canonical_url', models.URLField(blank=True, help_text='Leave blank to auto-generate from slug')),
                ('body_content', django_ckeditor_5.fields.CKEditor5Field(blank=True)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='uploads/featured_images/')),
                ('schema_json', models.TextField(blank=True, help_text='Paste raw JSON-LD structured data here')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='RelatedLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('open_new_tab', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_links', to='pages.page')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
