# Generated by Django 5.1.4 on 2026-04-21 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('maps', 'Maps'), ('my_india', 'My India')], default='general', help_text='Which section this page belongs to (used for nav tabs)', max_length=20),
        ),
    ]
