# Generated by Django 5.1.4 on 2026-04-23 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_add_category_to_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_image', models.ImageField(blank=True, help_text='Background image for the home page hero section', null=True, upload_to='uploads/hero/')),
                ('hero_title_line1', models.CharField(default='Discover India', help_text='First line of the hero heading', max_length=120)),
                ('hero_title_line2', models.CharField(default='Like Never Before', help_text='Second line (first word orange, last word green)', max_length=120)),
                ('hero_subtitle', models.CharField(default='Explore the rich tapestry of culture, heritage, landscapes, and stories that make India truly incredible.', help_text='Subtitle text below the heading', max_length=300)),
                ('hero_cta_text', models.CharField(default='Explore Now', help_text='Primary CTA button label', max_length=60)),
                ('hero_cta_url', models.CharField(default='/maps', help_text='Primary CTA button URL', max_length=200)),
                ('site_name', models.CharField(default='My India', max_length=100)),
                ('tagline', models.CharField(blank=True, default='Explore the rich tapestry of culture, heritage and stories that make India truly incredible.', max_length=255)),
                ('pages_per_section', models.PositiveSmallIntegerField(default=3, help_text='How many articles to preview per section on the home page')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
